# Generated by Django 4.0.1 on 2022-01-20 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_tag_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='image',
        ),
    ]
